#Automatic call to the API to keep alive, encrypted version
name: MS AutoSubscribeService with GitHub v2

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "12 * * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # Self-ordered start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #Install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #Installation requests
      run: |
        pip install requests
    - name: Read config from secrets  #Read Secret
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }} # secrets_id prepare
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }} # secrets_key prepare
      run: | 
        cp main.py temp.py
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_KEY > configkey.txt
        sed -i '10 r configid.txt' temp.py
        sed -i '12 r configkey.txt' temp.py
    - name: Test Api #ApiCall
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python temp.py
    - name: Delete secrets config #Delete secret config
      run: | 
        rm -f temp.py
        rm -f configid.txt
        rm -f configkey.txt    
    - name: Commit #Upload a new refresh_token to the repository
      run: |
        git config --global user.email kylejohnmarky075@gmail.com
        git config --global user.name MSAutoSubscribeService
        git add .
        git commit -m "Update new refresh token with MSO_E5_Dev_AutoRenew_REVISION_2" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
